spring.application.name=bankcardservice
server.port=8095

spring.datasource.url=jdbc:postgresql://localhost:5432/bankcarddb
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

cardSecretKey=gatewayCardSecretKey
paymentInternalSecretKey=paymentInternalSecretKey

spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=false