spring.application.name=bankapigateway

server.port=8765
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

gateway.secrets.account-service=gatewayAccountSecretKey
gateway.secrets.transaction-service=gatewayTransactionSecretKey
gateway.secrets.bankcardservice=gatewayCardSecretKey