spring.application.name=bankapigateway

server.port=8765
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

gateway.secrets.account-service=gatewayAccountSecretKey
gateway.secrets.transaction-service=gatewayTransactionSecretKey
gateway.secrets.bankcardservice=gatewayCardSecretKey
gateway.secrets.bankpaymentservice=gatewayPaymentSecretKey

gateway.vendorKey.TPay=gatewayTPayVendorKey

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=true

springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.configUrl=/v3/api-docs/swagger-config
springdoc.swagger-ui.use-root-path=true

#SWAGGER URLs
springdoc.swagger-ui.urls[0].url=/v3/api-docs
springdoc.swagger-ui.urls[0].name=API Gateway Service

springdoc.swagger-ui.urls[1].url=/bankauthservice/v3/api-docs
springdoc.swagger-ui.urls[1].name=Authentication Service

springdoc.swagger-ui.urls[2].url=/bankaccountservice/v3/api-docs
springdoc.swagger-ui.urls[2].name=Account Service

springdoc.swagger-ui.urls[3].url=/bankcardservice/v3/api-docs
springdoc.swagger-ui.urls[3].name=Card Service

springdoc.swagger-ui.urls[4].url=/banktransactionservice/v3/api-docs
springdoc.swagger-ui.urls[4].name=Transaction Service

springdoc.swagger-ui.urls[5].url=/bankpaymentservice/v3/api-docs
springdoc.swagger-ui.urls[5].name=Payment Service

#API ROUTES
spring.cloud.gateway.routes[0].id=bankauthservice
spring.cloud.gateway.routes[0].uri=lb://BANKAUTHSERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/bankauthservice/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[1].id=bankaccountservice
spring.cloud.gateway.routes[1].uri=lb://BANKACCOUNTSERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/bankaccountservice/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[2].id=bankcardservice
spring.cloud.gateway.routes[2].uri=lb://BANKCARDSERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/bankcardservice/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[3].id=banktransactionservice
spring.cloud.gateway.routes[3].uri=lb://BANKTRANSACTIONSERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/banktransactionservice/**
spring.cloud.gateway.routes[3].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[4].id=bankpaymentservice
spring.cloud.gateway.routes[4].uri=lb://BANKPAYMENTSERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/bankpaymentservice/**
spring.cloud.gateway.routes[4].filters[0]=StripPrefix=1