spring.application.name=bankauthservice
server.port=8080

spring.datasource.url=jdbc:postgresql://${POSTGRES_NETWORK:localhost}:5432/${POSTGRES_DB:bankauthdb}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}

paymentInternalSecretKey=paymentInternalSecretKey
interServiceSecretKey=interServiceSecretKey

spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.group-id=banking-system-simulator-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.value.default.type=com.tejas.bankingcommon.dto.OtpEvent
spring.kafka.consumer.properties.spring.json.use.type.headers=false

spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=false
