spring.application.name=bankcardservice
server.port=8095

spring.datasource.url=jdbc:postgresql://${POSTGRES_NETWORK:localhost}:5432/${POSTGRES_DB:bankcarddb}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}

spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

cardSecretKey=gatewayCardSecretKey
paymentInternalSecretKey=paymentInternalSecretKey
interServiceSecretKey=interServiceSecretKey

spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=false
